version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.12 # pick your Node version
    working_directory: ~/project # stay at repo root
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd PokemonSearch && yarn install
      - run:
          name: Build project
          command: cd PokemonSearch && yarn build
      - test:
          name: Run tests
          command: cd PokemonSearch && yarn test

workflows:
  build_and_test:
    jobs:
      - build
