version: 2.1

parameters:
  app-dir:
    type: string
    default: "PokemonSearch"

jobs:
  build:
    docker:
      - image: cimg/node:22.12
    working_directory: ~/project/<< parameters.app-dir >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build project
          command: yarn build

workflows:
  build_and_test:
    jobs:
      - build:
          app-dir: "PokemonSearch"
